server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: SECOND-SERVICE


  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
rabbitMQ:
    queueForSecondService:
      name: secondServiceQueue
    queueForThirdService:
      name: thirdServiceQueue
    exchange:
      name: myExchange
    routing:
      keyForSecondService: myRoutingKeyForSecondService
      keyForThirdService: myRoutingKeyForThirdService

